# Generated by Django 5.0.3 on 2024-04-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_userdata_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
