# Generated by Django 5.0.3 on 2024-04-26 23:13

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_live_streamer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='end_date',
            field=models.DateTimeField(validators=[business.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='live',
            name='start_date',
            field=models.DateTimeField(validators=[business.models.validate_future_date]),
        ),
    ]
