# Generated by Django 5.0.3 on 2024-04-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_live_end_date_alter_live_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
