# Generated by Django 5.0.3 on 2024-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_userdata_email_userdata_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='none', max_length=140),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(default='none', max_length=140),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(default='none', max_length=140),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='none', max_length=140),
        ),
    ]
