# Generated by Django 5.0.3 on 2024-05-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_live_streamer_name_live_streamer_pseudo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionsMaterial',
            new_name='OptionsMaterialLabel',
        ),
        migrations.RenameField(
            model_name='live',
            old_name='material',
            new_name='material_label',
        ),
        migrations.RenameField(
            model_name='optionsmateriallabel',
            old_name='name',
            new_name='label',
        ),
    ]
