# Generated by Django 5.0.3 on 2024-05-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_rename_optionsmaterial_optionsmateriallabel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsMaterialBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ManyToManyField(max_length=300, to='business.optionsmateriallabel')),
            ],
        ),
        migrations.AddField(
            model_name='live',
            name='material_brand',
            field=models.ManyToManyField(to='business.optionsmaterialbrand'),
        ),
    ]
