# Generated by Django 5.0.3 on 2024-04-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_userdata_email_remove_userdata_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pegi', models.IntegerField(default=None)),
                ('material', models.CharField(max_length=100)),
                ('streamer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.userdata')),
            ],
        ),
    ]
