# Generated by Django 5.0.3 on 2024-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_optionsmaterialbrand_live_material_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsmaterialbrand',
            name='brand',
        ),
        migrations.AddField(
            model_name='optionsmaterialbrand',
            name='brand',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
