# Generated by Django 5.0.3 on 2024-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_remove_optionsmaterialbrand_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='material_brand',
        ),
        migrations.AlterField(
            model_name='live',
            name='material_label',
            field=models.ManyToManyField(to='business.optionsmaterialbrand'),
        ),
        migrations.RemoveField(
            model_name='optionsmaterialbrand',
            name='brand',
        ),
        migrations.AddField(
            model_name='optionsmaterialbrand',
            name='brand',
            field=models.ManyToManyField(max_length=300, to='business.optionsmateriallabel'),
        ),
    ]
