# Generated by Django 5.0.3 on 2024-05-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_remove_live_material_brand_alter_live_material_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='material_label',
        ),
        migrations.RemoveField(
            model_name='optionsmaterialbrand',
            name='brand',
        ),
        migrations.CreateModel(
            name='LiveMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.live')),
                ('material_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.optionsmaterialbrand')),
                ('material_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.optionsmateriallabel')),
            ],
        ),
        migrations.AddField(
            model_name='live',
            name='material_labels',
            field=models.ManyToManyField(through='business.LiveMaterial', to='business.optionsmateriallabel'),
        ),
        migrations.AddField(
            model_name='optionsmaterialbrand',
            name='brand',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
