# Generated by Django 5.0.3 on 2024-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_live_material_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='material_brands',
            field=models.ManyToManyField(blank=True, through='business.LiveMaterial', to='business.optionsmaterialbrand'),
        ),
        migrations.AlterField(
            model_name='live',
            name='material_labels',
            field=models.ManyToManyField(blank=True, through='business.LiveMaterial', to='business.optionsmateriallabel'),
        ),
    ]
