# Generated by Django 5.0.3 on 2024-05-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_live_material_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='material_brands',
            field=models.ManyToManyField(through='business.LiveMaterial', to='business.optionsmaterialbrand'),
        ),
        migrations.AlterField(
            model_name='live',
            name='material_labels',
            field=models.ManyToManyField(through='business.LiveMaterial', to='business.optionsmateriallabel'),
        ),
        migrations.AlterField(
            model_name='livematerial',
            name='material_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.optionsmaterialbrand'),
        ),
        migrations.AlterField(
            model_name='livematerial',
            name='material_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.optionsmateriallabel'),
        ),
    ]
