# Generated by Django 5.0.3 on 2024-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_remove_optionsmaterialbrand_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='material_brands',
        ),
        migrations.RemoveField(
            model_name='live',
            name='material_labels',
        ),
        migrations.AddField(
            model_name='live',
            name='material_label',
            field=models.ManyToManyField(to='business.optionsmaterialbrand'),
        ),
    ]
