# Generated by Django 5.0.3 on 2024-05-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_remove_live_material_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='material_label',
        ),
        migrations.RemoveField(
            model_name='optionsmaterialbrand',
            name='brand',
        ),
        migrations.CreateModel(
            name='MaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.optionsmaterialbrand')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.optionsmateriallabel')),
            ],
        ),
        migrations.AddField(
            model_name='live',
            name='material_options',
            field=models.ManyToManyField(blank=True, to='business.materialoption'),
        ),
        migrations.DeleteModel(
            name='LiveMaterial',
        ),
        migrations.AddField(
            model_name='optionsmaterialbrand',
            name='brand',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
