# Generated by Django 5.0.3 on 2024-05-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_optionsmaterial_remove_materialoption_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.live')),
            ],
        ),
    ]
