# Generated by Django 4.1.13 on 2024-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_liveregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clic_nb', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('streamer_pseudo', models.CharField(max_length=50)),
            ],
        ),
    ]
