# Generated by Django 4.1.13 on 2024-05-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_livestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveStats',
        ),
    ]
