# Generated by Django 4.1.13 on 2024-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_livestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestats',
            name='live_id',
            field=models.CharField(default=19, max_length=24),
            preserve_default=False,
        ),
    ]
