# Generated by Django 4.1.13 on 2024-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_remove_livestats_live_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestats',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
