# Generated by Django 5.0.3 on 2024-04-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_live_streamer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='streamer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.userdata'),
        ),
    ]
