# Generated by Django 5.0.3 on 2024-05-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_userdata_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='streamer_name',
        ),
        migrations.AddField(
            model_name='live',
            name='streamer_pseudo',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='business.userdata'),
            preserve_default=False,
        ),
    ]
