# Generated by Django 5.0.3 on 2024-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_remove_live_material_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='materialoption',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='materialoption',
            name='label',
        ),
        migrations.RemoveField(
            model_name='live',
            name='material_options',
        ),
        migrations.AddField(
            model_name='live',
            name='material',
            field=models.ManyToManyField(blank=True, to='business.optionsmaterial'),
        ),
        migrations.DeleteModel(
            name='OptionsMaterialBrand',
        ),
        migrations.DeleteModel(
            name='OptionsMaterialLabel',
        ),
        migrations.DeleteModel(
            name='MaterialOption',
        ),
    ]
