# Generated by Django 4.1.13 on 2024-05-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_delete_livestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_nb', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('streamer_pseudo', models.CharField(max_length=50)),
            ],
        ),
    ]
