# Generated by Django 4.1.13 on 2024-05-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_alter_livestats_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestats',
            old_name='id',
            new_name='live_id',
        ),
    ]
