# Generated by Django 4.1.13 on 2024-05-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_rename_id_livestats_live_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkClick',
        ),
    ]
