# Generated by Django 4.1.13 on 2024-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_livestats_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
